title: My blog using Github Pages
author: Daniel Dieppa
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first site using Github pages

# social links
twitter_username: ddieppa
github_username:  ddieppa

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
